services:

  postgres:
    image: postgres:16
    container_name: library-postgres
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: library-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  backend:
    build:
      context: ./backend
    container_name: library-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mailhog

  frontend:
    build:
      context: ./frontend
    container_name: library-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data: