spring.application.name=library-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/library
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD

app.jwt.secret=YOUR_JWT_SECRET
app.jwt.expiration=3600000

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=YOUR_MAIL_USERNAME
spring.mail.password=YOUR_MAIL_PASSWORD